runtime: python39

# Static file serving for the web dashboard
handlers:
  # Serve main files
  - url: /
    static_files: web/index.html
    upload: web/index.html

  - url: /index.html
    static_files: web/index.html
    upload: web/index.html

  # Serve JavaScript
  - url: /dashboard.js
    static_files: web/dashboard.js
    upload: web/dashboard.js

  # Serve CSS
  - url: /style.css
    static_files: web/style.css
    upload: web/style.css

  # Serve any additional static files
  - url: /(.+)
    static_files: web/\1
    upload: web/.*

# Basic configuration
automatic_scaling:
  min_instances: 0
  max_instances: 1 